language: node_js
node_js: node
deploy: app:radiant-ridge-30841
  provider: heroku
  api_key:
    secure: U/WFatQYuQCwO299TNtIkG2vGczNnRp0DrO9MeuVY3OB/VN62PfrNCrn/XSP5no9FYH4BFZ0aK0sDFIXaz9REUiCVoVUeZObBXg3bKymG9PeXqv/GQFtOfpxq9tOX0creP8iUgk9vkJxg++lU3gnqQG05a54tzbgVtYfPNSFK1qK+HKHroFdNsdfFPZL1HOCZl4i3DE7Xw0gxVyqYPXNfy6apFOsS9UTyp0cj28TzOfEhIXGevtU8Z3HXPHWDmK46OWoRRN6Qphuq3xz0wz4BzLjcEnwYfnh1hJilGRbiYuobaEKPIccDIuhe2vtpUDXlxnNzlD8u9vOmxOaMHbGFJNXtf8AKlbMg0E1Xgc5EOKPg0iSLPqa3fQfIlMpdtx1IG64ugb9iCzzfQ62LBk3uFL7aAUt5rJDCoqoMMqtikA6sjr1mKlSipNTYL3jAuP1ozwFSryZDQc5N2OUcSLgtSxUcKsGafAw1Rv50Uz8QRUQDixMBtZT7Y0CQOHLWjZ8GnR0GcYkiksE0R/qrsRVuYg7ngEk533bmImUUNY74OTPaxR7N1a/iOVa0jUT+OWL2mAft+Efb5TEDL9PV2RYLYCq99w1JiFUo6P838CUJ47H5FbLMGPQDiurMCy/XelcO6rAeG0qbNfCxP8xo9LihPjub4u9tQsgeELAFwHCpa0=
  app: api_blog
  on:
    repo: laurawolf/api_blog
